# Generated by Django 2.1.7 on 2019-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_name_hindi', models.CharField(default='', max_length=100)),
                ('scheme_discription', models.TextField()),
                ('scheme_discription_hindi', models.TextField(default='')),
                ('scheme_image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_title_hindi', models.CharField(default='', max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
