version: '3'
services:
  db:
    image: postgresdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: sqluser
      POSTGRES_PASSWORD: sqlpassword
  web:
    depends_on:
      - db
    image: shikshakikiran
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn shikshakikiran.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - "8000:8000"