# Generated by Django 2.1.7 on 2019-03-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190310_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
