# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Environment variables to configure PostgreSQL
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=sqluser
ENV POSTGRES_PASSWORD=sqlpassword

# Expose the default PostgreSQL port (5432)
EXPOSE 5432