# Generated by Django 2.1.7 on 2019-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentschemes',
            name='scheme_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
