# Generated by Django 2.1.7 on 2019-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20190322_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentschemes',
            name='scheme_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
